name: PR Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - fidesctl/**
      - .github/workflows/test.yaml

env:
  CONTAINER: fidesctl:local
  IMAGE: ethyca/fidesctl:local

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build fidesctl container
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./fidesctl
          file: ./fidesctl/Dockerfile
          outputs: type=docker,dest=/tmp/${{ env.CONTAINER }}.tar
          push: false
          tags: ${{ env.IMAGE }}

      - name: Upload fidesctl container
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/${{ env.CONTAINER }}.tar
          retention-days: 7

  Fidesctl:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidesctl container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidesctl image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Check fidesctl installation
        run: make check-installation

      - name: Run fidesctl evaluation
        run: make fidesctl

  Black:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidesctl container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidesctl image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Run formatter
        run: make black

  Pylint:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidesctl container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidesctl image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Run linter
        run: make pylint

  Mypy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidesctl container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidesctl image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Run typechecker
        run: make mypy

  Xenon:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fidesctl container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidesctl image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Run cyclomatic complexity check
        run: make xenon

  Test:
    needs: Build
    runs-on: ubuntu-latest
    services:
      fidesctl-db:
        image: postgres:12
        env:
          POSTGRES_DB: fidesctl
          POSTGRES_PASSWORD: fidesctl
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Download fidesctl container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fidesctl image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Start fidesctl
        run: docker run ${{ env.IMAGE }}

      - name: Run test suite
        run: docker run ${{ env.IMAGE }} pytest -x
